### ISSUE TITLE
Error when using hooks

### ISSUE THREAD

**Issue by carloslfu** [transitive-bullshit/create-react-library#99] opened 2018-11-03 22:57 UTC
I'm bootstrapping a React component library with this tool and I get: `Hooks can only be called inside the body of a function component`.

Steps to reproduce:
- Create a library with `create-react-library`.
- Update `react` and `react-dom` to `v16.7.0-alpha.0` in `./package.json` and `./src/package.json`.
- Use new React hooks feature inside `src/`.

If you try the example you get the error. One weird thing is that if you use hooks in the `example` you don't get any error.

**Comment by monsterooo** [comment] 2018-11-15 17:35
I also encountered this problem, I am looking for a problem. 😤

**Comment by sag1v** [comment] 2018-12-02 12:08
Interesting, can you share a repo with an example?

**Comment by taylorham** [comment] 2018-12-08 06:19
I made a quick repro repo if that helps: https://github.com/taylorham/hooks-issue

**Comment by taylorham** [comment] 2018-12-14 00:59
I've found that the issue seems to come from using a `"link:.."` or `"file:.."` as the module source in `package.json`. If you push your project to a repository and set it with `"git+<some github url>"`, it should work fine.

However, now you've got to commit, push, and reinstall the package every time you want to view a change, which adds a LOT of friction to the process.

Building with your own `rollup.config.js` or even using Webpack yield the same results.

I'm not sure if this issue is with npm/yarn and how they're reading local dependencies, or if it's to do with `webpack-dev-server` just loading them differently.

It's definitely not a problem with `create-react-library`, but it'll affect a lot of its users once Hooks are more mainstream. Might be nice to join forces with whichever team the hiccup is coming from to find a solution.

Does anyone have a clue which tree I should start barking up? I feel like the React devs should be alerted since it's makes developing Hooks-based libraries a real slog.

**Comment by taylorham** [comment] 2018-12-15 01:40
Just found [this](https://github.com/facebook/react/issues/13991) today after a little more digging. So the React team is aware of it, and it occurs because of npm/yarn's resolution of `link`ed dependencies and loading 2 copies of React.

Dan has made [a](https://github.com/facebook/react/issues/14257) [few](https://github.com/facebook/react/issues/14317) [comments](https://github.com/facebook/react/issues/14262) addressing this, but it seems it's relatively expected and unlikely to change in the near future.

A good fix for now is to simply make your **library** depend on your **example**'s version of React by changing the **library**'s `package.json` entry to:
```json
"react": "link:./example/node_modules/react"
```

Hope this helps people who are itching to use Hooks ASAP!

**Comment by levrik** [comment] 2019-01-28 16:20
Neither @taylorham's nor @doasync's suggestion worked for me 😕

**Comment by doasync** [comment] 2019-01-29 21:51
@levrik, you probably have two different versions of react

**Comment by levrik** [comment] 2019-01-30 09:01
@doasync nope. I checked my bundle. It only includes one version of React. The issue is caused by another library which implements a custom renderer.

**Comment by antoniocapelo** [comment] 2019-02-08 16:48
I'm also experiencing this issue, tried installing the exact same version but still get the same hook call error.

**Comment by charliesbox** [comment] 2019-02-11 04:53
@antoniocapelo what I did was to remove react and react dom from `devDependencies`, as they are already `peerDependencies` in any parent project.

After that, it worked great.

**Comment by nickmcmillan** [comment] 2019-02-13 12:15
I found that @taylorham 's worked, but it also needed the same change made for `react-dom` as well.
So in `example/package.json`
```
"react": "link:../node_modules/react",
"react-dom": "link:../node_modules/react-dom"
```

Also FWIW, my parent `package.json` references version 16.8.1.
```
"react": "16.8.1",
"react-dom": "16.8.1"
```

Works fine.

**Comment by bwighthunter** [comment] 2019-04-19 04:33
Sorry, running into this now, Just curious when you say 
```"react": "16.8.1",
"react-dom": "16.8.1"```
Is this in peerDependencies? I am trying to figure out how to get this issue resolved.

**Comment by markau** [comment] 2019-04-21 13:44
@bwighthunter read it again, the change gets made in `example/package.json`, there is no `peerDependencies` in that lower level `package.json`

**Comment by filipdanic** [comment] 2019-05-14 10:25
Seems like you also have to update `"react-scripts": "file:../node_modules/react-scripts",` in `example/package.json`

This PR seems good: https://github.com/transitive-bullshit/create-react-library/pull/134/files

**Comment by abhimanyuPathania** [comment] 2019-05-25 10:28
I had to explicitly run `yarn install` in the `examples` directory after applying solution given by @nickmcmillan

**Comment by djnorrisdev** [comment] 2019-06-21 21:20
I'm a beginner to this, so I don't know how to actually integrate my solution into create-react-library (yet). I've updated all the babel and react packages, and posted it to [my github](https://github.com/djnorrisdev/npm-component-creator). It doesn't have the cool walkthrough of package creation that `npx create-react-library` generates when installing, but I want to do a proper fix when I figure out how to do it. This fix happened because `@material/core` now uses react hooks under the hood, and breaks create-react-library.

**Comment by corysimmons** [comment] 2019-06-28 17:33
This is a problem caused by 2 different versions of React being used: 1 for the React component you're trying to bundle up, 1 for the React example you're using.

One of them loads first, and when your hooky component gets loaded, another React fires up and is like "Whoa! You can't do hook stuff right here!"

The best way I've found around this is to completely give up on `npm/yarn link` and use https://github.com/whitecolor/yalc

It's not perfectly convenient as it's not a symlink and you have to reinstall your local pkg every time you want to test it, but at least you can get around this hook/link seemingly unsolvable problem.

**Comment by vagyriag** [comment] 2019-08-29 16:04
@corysimmons  I LOVE YOU, yalc was the only thing that worked for me.

**Comment by corysimmons** [comment] 2019-08-29 16:46
Forgot to update my comments on this kind of stuff, but yalc _can_ be config'd to just auto-update the pkg you're working on using nodemon (or any cli watcher).

Add `"watch:yalc": "nodemon -x yalc push"` to your `"scripts"` object in `package.json` in the lib you're creating. And obviously run it.

Now every time you change anything in your local lib, it will update that pkg anywhere it has been installed (locally) automatically.

I love you too @vagyriag 💖

**Comment by Andycharalambous** [comment] 2020-01-23 17:27
Unfortunately this doesn’t appear to trigger a hot reload in the example app - but at least the hooks errors are gone.

**Comment by KhaledAylii** [comment] 2020-02-27 02:18
I know this might not be the answer you're looking for, but according to React docs, this is not an error, but a feature by design. You can find the reference here: [https://reactjs.org/docs/hooks-overview.html](url)

<img width="892" alt="Screen Shot 2020-02-26 at 9 16 44 PM" src="https://user-images.githubusercontent.com/15389069/75406064-7dcfab80-58dd-11ea-9cc4-7a4536f6d2b9.png">

**Comment by transitive-bullshit** [comment] 2020-03-31 00:13
I believe this should now be fixed via https://github.com/transitive-bullshit/create-react-library/pull/151/ and the other major changes made in the latest `v3` release.

Please let me know if this is not the case.

**Closed** 2020-03-31 00:56 UTC

**Comment by BRoy98** [comment] 2021-11-19 20:09
> I know this might not be the answer you're looking for, but according to React docs, this is not an error, but a feature by design. You can find the reference here: [https://reactjs.org/docs/hooks-overview.html](url)
> 
> <img alt="Screen Shot 2020-02-26 at 9 16 44 PM" width="892" src="https://user-images.githubusercontent.com/15389069/75406064-7dcfab80-58dd-11ea-9cc4-7a4536f6d2b9.png">

Not sure why this answer does not have any positive reactions. I was having the same error, I added hook in a regular JS function instead of React function. Thanks, man! 🎉
