### ISSUE TITLE
ENOENT: no such file or directory, open 'stream'

### ISSUE THREAD

**Issue by rkhayat** [transitive-bullshit/create-react-library#89] opened 2018-10-22 01:23 UTC
Related - https://github.com/transitive-bullshit/create-react-library/issues/22

The first issue I experienced was after installing styled-components (rollup v0.64.1)
`
[!] Error: 'isElement' is not exported by node_modules\react-is\index.js
`

I solved this by changing commonjs's config in rollup.config.js

`

    commonjs({
      include: 'node_modules/**',
      namedExports: {
        'node_modules/react-is/index.js': ['isElement','isValidElementType','ForwardRef']
      }
    })
`

Now I am able to start the app, After saving any file in /src/, the terminal crashes

`
[!] Error: Could not load stream (imported by .....\node_modules\styled-components\dist\styled-components.esm.js): ENOENT: no such file or directory, open 'stream'
`

The terminal displays this warning on starting rollup server
`
preferring built-in module 'stream' over local alternative at...
`

Adding the following to rollup.config.js solves the warning, however a new error appears... (this time the terminal in /example/ when I load  localhost:3000 )
`
resolve({preferBuiltins:false}),
`

`
TypeError: emitter is not a constructor
773 | Stream.prototype = new emitter();
dist/index.es.js:773
`

**Comment by transitive-bullshit** [comment] 2018-10-22 15:42
Do you have a GitHub repo you can point me to that I can try and debug the issue for you?

**Comment by rkhayat** [comment] 2018-10-22 16:08
Thank you for checking, much appreciated. https://github.com/rkhayat/rollup-issue

**Comment by robowen5mac** [comment] 2018-11-14 18:20
I am seeing the same issue. Any leads on how to resolve?

**Comment by daleyjem** [comment] 2019-01-02 17:47
For me, this seemed to only error out when bundling from `--watch`, even though the initial bundle would only warn on external dependencies. I don't like that I'd have to include a full array of external dependencies, so I included this:

```js
external: (id) => {
  return !id.substring(0, 1).match(/(\.|\/)/)
}
```

**Comment by philip-peterson** [comment] 2019-04-17 15:52
I am experiencing this issue too. @transitive-bullshit , could you shed some light on the cause of the problem and why this issue is closed, please? Thanks!

**Comment by transitive-bullshit** [comment] 2019-04-17 20:41
Hey @philip-peterson, reopened the issue for others to comment on.

I'm pretty busy these days so I won't have a chance to look myself for a little while.

Good luck!

**Comment by transitive-bullshit** [comment] 2020-03-31 00:57
This should be fixed now with the latest `v3` release. `v3` uses `microbundle` under the hood, so if you're seeing any issues like this please check there first.

Please open a new issue if you're still seeing errors.

**Closed by transitive-bullshit** 2020-03-31 00:57 UTC
